### ISSUE TITLE
Give credit where credit is due

### ISSUE THREAD

**Issue by JakeHartnell** [0xkdavid/cw20-bonding#2]
This is a fork, but you've erased all mention of the previous authors: https://github.com/CosmWasm/cw-tokens/tree/main/contracts/cw20-bonding

Be a good open source contributor please. : )

**Comment by 0xkdavid** [comment]
@JakeHartnell sure, I'm planning to get started with original cw20-bonding, and will update more with my own algorithm. It's WIP for now.
